language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PpbegzG9ZUpXDYDGFF+hZ91d3m0Y/63WW+sEBLE8Gyt+Zb73WmF4DbDdhr+cSg5V/YchwSFk1SEGNfAM6QkqPkJQ0d1G19pueepHTZecL7BTPgml/0NqIpDobs5mg0WYa5GKX+Ct3QBpT0QcAawy0kBJzG9dhMmtQ2dXrnVg48Q=
  file:
    - 'hedges.js'
    - 'hedges.min.js'
  on:
    tags: true
