language: node_js
script: npm run-script test-travis
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
after_script: npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls
sudo: false
deploy:
  provider: npm
  email: tituswormer@gmail.com
  api_key:
    secure: FD133yHar5vQBDxqB9RZIsseEbl7+1AFCi7PdaSy/CvNwt4yStQlEm/WgK8gFwtPBlL0QMYPDJzeDE5w8bIc5m/3pvP4lDaWLTnxqemlH353rD6tmRkn/egjdg3/jj63hN9sZeo8ZRQHvrFWUKypCV356bVtf/DAZbALavy3w28=
  on:
    repo: wooorm/hedges
